engaging-computing/MYR

src/myr/Myr.js
Let user set coordinates for position one at a time
=> Let user set coordinates for position one at a time

src/components/Reference.js, src/components/View.js, src/css/App.css, src/myr/Group.js, src/myr/Myr.js, src/myr/reference.js, src/reducers/editor.js
Added colours to variables of certain types, added Animations section
=> Updated and coloured reference section

src/components/Header.js, src/components/Reference.js, src/css/App.css, src/myr/reference.js
Changed icons, added key to reference, style changes
=> Reference style updates

src/components/Header.js, src/components/Reference.js
Aesthetic changes to the login/avatar experience
=> Login button changes

package.json, src/components/Header.js, src/components/MyrTour.js, src/components/Reference.js, src/components/View.js, src/containers/Guided.js, src/containers/Ide.js, src/myr/Group.js, src/myr/Myr.js, src/reducers/editor.js, src/routes.js, yarn.lock
In this pull request, I wanted to make it easier to get started with the system. 
Changed the lookup process in MYR to use the ID of the object. This changes it from a plain array to an associative array/ JS Object. This graph can be rendered in MYR as before.
Using Reactour, the Tour will point out basic aspects of the editor.
The default on load message has also been changed to direct them to learnmyr.org/first-time. There they will see the basic usage of MYR.
This will need a new yarn lock.
=> Tour, Responsive Help, New Default message and MYR Entity Graph

src/components/View.js, src/myr/Myr.js
Added tubes and lines for chem models
=> added tube and line to MYR API

src/components/Lesson.js, src/firebase.js
=> Logout Bug and Lesson Nav Button Fix

src/components/Header.js
=> Save window does not appear when using ctrl+s

src/actions/courseActions.js, src/components/Course.js, src/components/View.js, src/containers/Ide.js, src/css/App.css, src/css/CourseSelect.css
=> Lesson overflow txt scrolls

src/components/CourseSelect.js, src/components/MyrTour.js, src/myr/Myr.js
=> Update tour and bools for animations

src/components/Header.js
=> Updated save error message

src/actions/editorActions.js, src/actions/sceneActions.js, src/components/Classroom.js, src/components/Header.js, src/components/ReferencePage.js, src/components/SceneConfigMenu.js, src/components/View.js, src/components/layouts/Classroom.js, src/components/layouts/Guided.js, src/components/layouts/Ide.js, src/components/layouts/Reference.js, src/constants/ActionTypes.js, src/constants/LayoutTypes.js, src/containers/Reference.js, src/css/ReferencePage.css, src/myr/Myr.js, src/reducers/scene.js, src/routes.js
Addresses #116, #118, #114, and #143
=> Scene reducer updates, dedicated reference page, and classroom bug fix

src/myr/Myr.js, src/myr/reference.js
Reverts engaging-computing/MYR#166
=> Revert "Added setPhiLength() to reference"

src/myr/Myr.js, src/myr/reference.js
Reverts engaging-computing/MYR#167
=> Revert "Revert "Added setPhiLength() to reference""

src/components/customCompleter.js, src/myr/Myr.js, src/myr/reference.js, src/tests/Myr.test.js
Reverts engaging-computing/MYR#184
=> Revert "Moved animation properties to the cursor and added shiftToColor()"

src/components/customCompleter.js, src/myr/Myr.js, src/myr/reference.js, src/tests/Myr.test.js
Reverts engaging-computing/MYR#185
=> Revert "Revert "Moved animation properties to the cursor and added shiftToColor()""

src/components/Header.js, src/components/MyrTour.js, src/components/Reference.js
addresses bug [#183](https://github.com/engaging-computing/MYR/issues/183).
=> Fixed bug where tour could open with reference open, and also disables tour when reference page was opened.

src/components/Reference.js, src/components/customCompleter.js, src/css/App.css, src/myr/reference.js
Took out faulty functions, updated text completion, added examples.
=> Reference example links added

src/actions/courseActions.js
create a new commit in different branch to hope that it didn't highlight unnecessary code
=> Saving on course will auto populate the title and description of the Lesson on saving tab

src/components/structural/View.js
Reverts engaging-computing/MYR#274
Loading screen breaks image previews
=> Revert "Fixed typo in loading screen implementation"

src/myr/Myr.js, src/myr/reference.js, src/tests/Myr.test.js
Reverts engaging-computing/MYR#295
The below code failed to function as expected.
```
let colors = ["blue","pink"];
getRandomColor(colors);
box();
```
=> Revert "Adds ability to pass array to getRandomColor()"

src/components/structural/header/ProjectView.js
There were two exact same functions in ProjectView.js in components. So I remove one of them.
=> remove duplicate function

src/components/structural/View.js
=> Fixed issue where editor overlays view for iPhones

README.md, package.json, src/components/reference/Reference.js, src/css/App.css, yarn.lock
- Reference tooltips are no longer covered by the drawer
=> 1.5.3 | Reference Tooltips bug fix

src/components/structural/header/Header.js
=> Unsaved changes are caught in Firefox

src/components/structural/header/SceneConfigMenu.js
Issue was a malformed function call.  This will resolve #366
=> Resolved Collections issue

src/components/structural/header/SceneConfigMenu.js
=> Browsers request confirmation before unload after editing a setting

src/components/structural/header/SceneConfigMenu.js
- Fixed save prompt issues where if you modify a setting, and revert it back to the original value
- Fixed issue where setting the fly toggle would erase unrendered text
=> Saving settings fixes

src/components/layouts/Collection.js
This problem was found in the dev server.
=> Fix where collection page shows prompt for every refresh

src/actions/courseActions.js
Frontend courses now work with [API update for Backend](https://github.com/engaging-computing/MYR-backend/pull/142).
=> API updates

src/components/structural/header/Header.js, src/components/structural/header/SceneConfigMenu.js
Fixed the settings saving the placeholder scene's settings instead of the loaded scene.
=> Fixed setting save prompt again.

src/actions/courseActions.js, src/components/layouts/Guided.js
Removed extraneous (and invisible) "/>" below the lesson box.
Added error catching for courses without any lessons.
=> Course Lesson Fixes

src/components/layouts/Ide.js, src/components/structural/header/Banner.js, src/components/structural/header/Header.js
Adds a banner that will show user notifications about server downtime, updates, etc
=> Notification Banner

src/components/structural/header/Banner.js
Fixes link button text and border color, dismiss button color, and updated title's spacing
=> Banner Bugfixes

src/myr/Myr.js
=> setColor function works properly

public/index.html, src/actions/collectionActions.js, src/actions/courseActions.js, src/actions/editorActions.js, src/components/reference/ReferencePage.js
-     blank page: "MYR"
-     page with scene: "scene_name | MYR"
-     page with courses: "course_name Course | MYR"
-     page with collection: "collection_name Collection | MYR"
-     reference page: "Reference | MYR"
Also need to flip the titles in about page
=> New title for the pages

src/actions/referenceExampleActions.js
#419 
The format is
`functionName Reference | MYR`
=> Add title for reference exmaple page

src/actions/editorActions.js, src/actions/referenceExampleActions.js, src/components/structural/header/Header.js
we also have to set up a corresponding view in the GA
=> Add a line of code to send userid to GA

src/myr/Myr.js
setRotation was missing a default value for the x parameter.
=> Added missing default parameter

src/components/layouts/Ide.js, src/components/structural/header/Header.js
This closes out issue #400.
Also fixed small typo in IDE.js
=> fixed save sync confirmation box not appearing

src/myr/Myr.js, src/myr/reference.js, src/tests/Myr.test.js
This adds the ability to create translucent objects in MYR.
=> Object transparency

package-lock.json, package.json, src/components/collection/Collection.js, src/components/courses/Course.js, src/components/courses/CourseSelect.js, src/components/reference/RefExInfo.js, src/components/reference/Reference.js, src/components/reference/ReferencePage.js, src/components/structural/WelcomeScreen.js, src/components/structural/header/Header.js, src/components/structural/header/ProjectView.js, src/components/structural/header/SceneConfigMenu.js, src/components/structural/header/Sidebar.js
There's some text size change on reference page but everything else should be exactly same.
#424
=> Updated the @material-ui/core to latest version(4.11.2) 

src/components/structural/View.js, src/utils/AframeReg.js
This was causing a black image when saved a scene.
=> Fix preview image issue with scenelayer

README.md, package-lock.json, package.json
Update README, and package.json to new MYR version
=> Changes to README and package.json for new version

.github/workflows/deploy_beta.yml, .github/workflows/deploy_prod.yml, Dockerfile
Added build arg for the docker image, updated pipeline to use it.
=> Added build-time arg for google client id

src/components/structural/View.js
Note: issue only exists in dev right now, is not present in prod.
=> Fixes bug where spacebar keypresses get caught before reaching ace editor

src/components/structural/View.js, src/utils/AFramePhysics.js, src/utils/AframeRegIndicator.js, src/utils/WASDPlusControls.js
Reference threejs from aframe to ensure the two are compatible.
Also change the name "layer" to "setlayer" because it will conflict with the [layer](https://aframe.io/docs/1.2.0/components/layer.html) component in the latest aframe version.
=> Fixed the indicator freeze the MYR scene

src/utils/browserType.js
This fixes the flying controls by improving user agent checking using AFrame's device.
Previously MYR thought that chrome was a VR headset, this fixes it, but will require testing.
=> Flying Control Fixes

README.md, package.json
Updates README and `package.json` to show 2.3.0 changes
=> Pre 2.3.0 release changes

src/myr/Myr.js, src/tests/Myr.test.js
#481 
The problem was the color that sets in animation property was getting wrong element from the array of material when split the string.
Also, I added a tests for colorShift to prevent this from happening in the future.
=> Fixed colorshift bug and added test

src/components/structural/View.js, src/utils/AFramePhysics.js
Sidenote: there is a scene with the dice that always collide into the center of the plane and the problem with that is not really physics fault, but with how apply group with physics cause unexpected behavior.
=> Fixed makePushable not able to push the entity

README.md, package.json
Updated README with 2.2.2 changes and upped patch version number
=> Release candidate 2.3.1

src/components/editor/KeyboardShortcut.js, src/css/KeyboardShortcut.css, src/utils/AFramePhysics.js
=> Fixed the grammar for keyboard shortcuts

README.md, package.json
A release candidate for version 3.0.0.
=> Release Canidate 3.0.0

src/myr/reference.js
=> Fixed typo on point light reference text

README.md, package.json
Ignore the branch name I'm too lazy to fix it.
- Updated sorting for user projects to be case insensitive.
- Added ability to change code font size for an account.
- Added transparency to helper grid
- Additional Documentation for development.
- Misc. Dependency updates
=> Release Canidate 3.1.0

package-lock.json
Reverts engaging-computing/MYR#543
=> Revert "Bump nanoid from 3.1.25 to 3.3.1"

README.md, package.json
- Patched font-size bug, previously changing font-size would clear code in the editor   
- Dependency updates
- nvmrc file updated (10.13 -> 12.18)
=> Updating MYR 3.1.0 -> 3.1.1

src/components/structural/header/ProjectView.js
Fixed issue targeting legacy scenes that have no name crashing the application
=> Project Sorting Hotfix

README.md, package.json
Updates metadata for release 3.1.2
=> Release Canidate 3.1.2

README.md, package-lock.json, package.json, src/components/structural/header/ProjectView.js
Fixes a bug where a scene without a name can crash the client application.
This closes #563
=> Version 3.1.2

src/components/editor/FontSize.js, src/components/editor/KeyboardShortcut.js, src/myr/tour.js
Added two new segments to the tour on MYR, one for the keyboard shortcuts button, and one for the font size button
=> Added the font size and keyboard shortcut buttons to the tour

src/components/courses/Course.js
@RJMaradiaga and I created a progress bar for courses that shows you how far you are in completing it. Ryan did most of the work, I helped with minor things along the way
=> Added a progress bar to courses (Done by Ryan and myself)

src/components/structural/WelcomeScreen.js
Moved changes from the old WelcomeControls branch into a different branch named new_WelcomeControls
=> Added movement controls to welcome screen

.github/pull_request_template.md, src/components/structural/header/Header.js, src/components/structural/header/SceneConfigMenu.js
PR moves the reset button from the scene configuration drop-down menu to the header to make it easier for the user to reset their scene 
attached.
=> Reset button

package-lock.json, src/components/layouts/ReferenceExample.js, src/components/structural/View.js
On both production and dev, vertical movement had stopped working. I changed the View.js file, because in some previous commit, `wasd-plus-controls` was changed to `wasd-controls`, which only controls horizontal movement. So, the `a-camera` entity now has both of these attributes, so that, if needed, we can change the way vertical and horizontal speeds are handled independently of each other.
#657
=> Fixed Vertical Movement

package-lock.json, src/components/layouts/ReferenceExample.js
Fixes the issue with reference examples not showing up - this was fixed before but somehow broke again, so I just implemented the same changes again
=> References fix

package-lock.json, src/components/layouts/ReferenceExample.js, src/components/structural/View.js
Reverts engaging-computing/MYR#662
=> Revert "Fixed Vertical Movement"

src/components/structural/View.js
I have an easy fix for vertical movement, just had to figure out how to properly push it. I think this should work
N/A
#657
=> Vertical movement fix - third try

src/components/structural/View.js
Same fix as done in dev, but this time for master
=> Vertical Movement Fix for Master
